import os
import io
import json
import re
import oracledb
from functools import wraps
from dotenv import load_dotenv
from flask import Flask, render_template, request, jsonify, Response, session, redirect, url_for
from PyPDF2 import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEndpointEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.chains.question_answering import load_qa_chain
from langchain.prompts import PromptTemplate
import firebase_admin
from firebase_admin import credentials as fb_credentials
from firebase_admin import auth as fb_auth
from firebase_admin import firestore as fb_firestore


load_dotenv()
app = Flask(__name__)

ADMIN_USERNAME = "Admin"
ADMIN_PASSWORD = "Password"

api_key = os.getenv("GEMINI_API_KEY")

_vector_store_cache = {}  

DEFAULT_SESSION_CONTEXT = {
    "course_outcomes": "",
    "bloom_level": "Understand",
    "weightage": "",
    "language": "",
    "yt_url": "",
    "study_mode": "normal",
    "vibe_type": "default",
}


PREUPLOADED_BOOKS = [
    {
        "id": "python-book",
        "title": "Python Book",
        "author": "Anonymous",
        "subject": "Python Programming",
        "filename": "python_book.pdf",
    },
    {
        "id": "art-of-data-science",
        "title": "Art of Data Science",
        "author": "Anonymous",
        "subject": "Data Science",
        "filename": "art_of_data_science.pdf",
    },
    {
        "id": "project-management",
        "title": "Project Management",
        "author": "Anonymous",
        "subject": "Project Management",
        "filename": "project_management.pdf",
    },
    {
        "id": "numerical-methods-in-finance",
        "title": "Numerical Methods in Finance",
        "author": "Anonymous",
        "subject": "Finance",
        "filename": "numerical_methods_in_finance.pdf",
    },
    {
        "id": "financial-management",
        "title": "Financial Management",
        "author": "Anonymous",
        "subject": "Finance",
        "filename": "financial_management.pdf",
    },
    {
        "id": "human-resource-management",
        "title": "Human Resource Management",
        "author": "Anonymous",
        "subject": "Human Resources",
        "filename": "human_resource_management.pdf",
    },
]

BOOKS_DIR = os.path.join(app.root_path, "static", "books")

ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_DSN = os.getenv("ORACLE_DSN")


def get_db():
    conn = oracledb.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=ORACLE_DSN
    )
    return conn


def _dict_row(cursor, row):
    if row is None:
        return None
    columns = [col[0].lower() for col in cursor.description]
    result = {}
    for col, val in zip(columns, row):
        if isinstance(val, oracledb.LOB):
            val = val.read()
        result[col] = val
    return result


def _dict_rows(cursor, rows):
    if not rows:
        return []
    columns = [col[0].lower() for col in cursor.description]
    result = []
    for row in rows:
        d = {}
        for col, val in zip(columns, row):
            if isinstance(val, oracledb.LOB):
                val = val.read()
            d[col] = val
        result.append(d)
    return result


def _fetchone(cur):
    row = cur.fetchone()
    return _dict_row(cur, row)


def _fetchall(cur):
    rows = cur.fetchall()
    return _dict_rows(cur, rows)


def _getid(var):
    val = var.getvalue()
    if isinstance(val, list):
        return int(val[0]) if val else None
    return int(val) if val is not None else None


def _ensure_column(conn, table, column, coltype_and_default):
    cur = conn.cursor()
    cur.execute(
        """SELECT COUNT(*) FROM user_tab_columns
           WHERE UPPER(table_name) = UPPER(:1) AND UPPER(column_name) = UPPER(:2)""",
        (table, column)
    )
    row = cur.fetchone()
    if row and row[0] == 0:
        plsql = f"""
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE {table} ADD {column} {coltype_and_default}';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
        """
        cur.execute(plsql)
        conn.commit()


def init_db():
    ddl_statements = [
        """CREATE TABLE questions (
            id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            topic          VARCHAR2(4000),
            difficulty     VARCHAR2(100)  NOT NULL,
            question_text  CLOB           NOT NULL,
            option_a       VARCHAR2(4000) NOT NULL,
            option_b       VARCHAR2(4000) NOT NULL,
            option_c       VARCHAR2(4000) NOT NULL,
            option_d       VARCHAR2(4000) NOT NULL,
            correct_option VARCHAR2(10)   NOT NULL,
            explanation    CLOB,
            source_title   VARCHAR2(4000),
            created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        """CREATE TABLE tests (
            id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            difficulty         VARCHAR2(100)  NOT NULL,
            num_questions      NUMBER         NOT NULL,
            source_title       VARCHAR2(4000),
            created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            user_id            NUMBER,
            competency_applied NUMBER DEFAULT 0
        )""",

        """CREATE TABLE test_questions (
            test_id        NUMBER NOT NULL,
            question_id    NUMBER NOT NULL,
            question_order NUMBER,
            CONSTRAINT fk_tq_test     FOREIGN KEY (test_id)     REFERENCES tests (id) ON DELETE CASCADE,
            CONSTRAINT fk_tq_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE test_attempts (
            id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            test_id  NUMBER NOT NULL,
            score    NUMBER NOT NULL,
            total    NUMBER NOT NULL,
            taken_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            user_id  NUMBER,
            CONSTRAINT fk_ta_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE users (
            id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UID"       VARCHAR2(4000) UNIQUE NOT NULL,
            name        VARCHAR2(4000) NOT NULL,
            age         NUMBER,
            phone       VARCHAR2(100),
            email       VARCHAR2(4000) NOT NULL,
            department  VARCHAR2(4000),
            designation VARCHAR2(4000),
            status      VARCHAR2(50)   DEFAULT 'active',
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        """CREATE TABLE user_education (
            id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id     NUMBER NOT NULL,
            degree      VARCHAR2(4000),
            institution VARCHAR2(4000),
            year        VARCHAR2(50),
            CONSTRAINT fk_ue_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE user_skills (
            id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id          NUMBER NOT NULL,
            skill_name       VARCHAR2(4000) NOT NULL,
            self_rated_level VARCHAR2(100),
            CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE user_experience (
            id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id      NUMBER NOT NULL,
            role         VARCHAR2(4000),
            organization VARCHAR2(4000),
            duration     VARCHAR2(200),
            description  CLOB,
            CONSTRAINT fk_uexp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE skill_reports (
            id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id          NUMBER NOT NULL,
            test_id          NUMBER,
            overall_score    NUMBER NOT NULL,
            overall_total    NUMBER NOT NULL,
            skills_breakdown CLOB,
            generated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_sr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT fk_sr_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE SET NULL
        )""",

        """CREATE TABLE user_answers (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            test_id         NUMBER NOT NULL,
            question_id     NUMBER NOT NULL,
            selected_option VARCHAR2(10),
            answered_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_ua_test     FOREIGN KEY (test_id)     REFERENCES tests (id) ON DELETE CASCADE,
            CONSTRAINT fk_ua_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE skill_competency (
            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id       NUMBER NOT NULL,
            skill_name    VARCHAR2(4000) NOT NULL,
            correct_count NUMBER DEFAULT 0 NOT NULL,
            total_count   NUMBER DEFAULT 0 NOT NULL,
            updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_skill_competency UNIQUE (user_id, skill_name),
            CONSTRAINT fk_sc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )""",

        """CREATE TABLE progress_snapshots (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id         NUMBER NOT NULL,
            test_id         NUMBER,
            overall_percent NUMBER NOT NULL,
            taken_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_ps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT fk_ps_test FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE SET NULL
        )""",

        """CREATE TABLE skill_fallback_topics (
            skill_name   VARCHAR2(4000) PRIMARY KEY,
            topics_json  CLOB,
            generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        """CREATE TABLE user_staged_files (
            id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_uid   VARCHAR2(4000) NOT NULL,
            filename   VARCHAR2(4000) NOT NULL,
            source     VARCHAR2(50)   NOT NULL,
            title      VARCHAR2(4000),
            file_blob  BLOB           NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        """CREATE TABLE user_vector_chunks (
            user_uid    VARCHAR2(4000) PRIMARY KEY,
            chunks_clob CLOB NOT NULL,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",
    ]

    conn = get_db()
    cur = conn.cursor()
    for ddl in ddl_statements:
        try:
            cur.execute(ddl)
            conn.commit()
        except Exception:
            conn.rollback()

    _ensure_column(conn, "users", "status", "VARCHAR2(50) DEFAULT 'active'")
    _ensure_column(conn, "tests", "user_id", "NUMBER")
    _ensure_column(conn, "test_attempts", "user_id", "NUMBER")
    _ensure_column(conn, "tests", "competency_applied", "NUMBER DEFAULT 0")

    conn.close()


def _update_skill_competency_and_progress(user_id, test_id):
    conn = get_db()
    cur = conn.cursor()

    cur.execute("SELECT competency_applied FROM tests WHERE id = :1", (test_id,))
    already_applied = _fetchone(cur)
    if not already_applied or already_applied["competency_applied"]:
        conn.close()
        return

    cur.execute("SELECT skill_name FROM user_skills WHERE user_id = :1", (user_id,))
    skill_rows = _fetchall(cur)
    declared_skills = {r["skill_name"].strip().lower(): r["skill_name"] for r in skill_rows if r["skill_name"]}

    if not declared_skills:
        cur.execute("UPDATE tests SET competency_applied = 1 WHERE id = :1", (test_id,))
        conn.commit()
        conn.close()
        return

    cur.execute(
        """SELECT q.topic, q.correct_option, ua.selected_option
           FROM test_questions tq
           JOIN questions q ON q.id = tq.question_id
           LEFT JOIN user_answers ua ON ua.test_id = tq.test_id AND ua.question_id = q.id
           WHERE tq.test_id = :1""",
        (test_id,)
    )
    rows = _fetchall(cur)

    matched_any = False
    for r in rows:
        topic_key = (r["topic"] or "").strip().lower()
        if topic_key not in declared_skills:
            continue  

        matched_any = True
        skill_name = declared_skills[topic_key]
        is_correct = 1 if r["selected_option"] and r["selected_option"] == r["correct_option"] else 0

        cur.execute(
            """MERGE INTO skill_competency sc
               USING (SELECT :1 AS user_id, :2 AS skill_name, :3 AS is_correct FROM DUAL) src
               ON (sc.user_id = src.user_id AND sc.skill_name = src.skill_name)
               WHEN MATCHED THEN UPDATE SET
                   sc.correct_count = sc.correct_count + src.is_correct,
                   sc.total_count   = sc.total_count + 1,
                   sc.updated_at    = CURRENT_TIMESTAMP
               WHEN NOT MATCHED THEN INSERT (user_id, skill_name, correct_count, total_count)
                   VALUES (src.user_id, src.skill_name, src.is_correct, 1)""",
            (user_id, skill_name, is_correct)
        )

    if matched_any:
        cur.execute(
            "SELECT correct_count, total_count FROM skill_competency WHERE user_id = :1", (user_id,)
        )
        competency_rows = _fetchall(cur)
        percents = [
            round((c["correct_count"] / c["total_count"]) * 100)
            for c in competency_rows if c["total_count"] > 0
        ]
        overall_percent = round(sum(percents) / len(percents)) if percents else 0

        cur.execute(
            "INSERT INTO progress_snapshots (user_id, test_id, overall_percent) VALUES (:1, :2, :3)",
            (user_id, test_id, overall_percent)
        )

    cur.execute("UPDATE tests SET competency_applied = 1 WHERE id = :1", (test_id,))
    conn.commit()
    conn.close()


def _backfill_skill_competency():
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        """SELECT DISTINCT t.id, t.user_id FROM tests t
           JOIN test_attempts ta ON ta.test_id = t.id
           WHERE t.user_id IS NOT NULL AND (t.competency_applied IS NULL OR t.competency_applied = 0)"""
    )
    pending = _fetchall(cur)
    conn.close()

    for row in pending:
        _update_skill_competency_and_progress(row["user_id"], row["id"])


init_db()
_backfill_skill_competency()


def _init_firebase_admin():
    if firebase_admin._apps:
        return
    sa_json = os.getenv("FIREBASE_SERVICE_ACCOUNT_JSON")
    if sa_json:
        cred = fb_credentials.Certificate(json.loads(sa_json))
    else:
        cred = fb_credentials.Certificate(
            os.getenv("FIREBASE_SERVICE_ACCOUNT_PATH", "firebase-service-account.json")
        )
    firebase_admin.initialize_app(cred)


_init_firebase_admin()
fs_db = fb_firestore.client()


def require_uid(view_func):
    @wraps(view_func)
    def wrapped(*args, **kwargs):
        auth_header = request.headers.get("Authorization", "")
        token = auth_header[7:] if auth_header.startswith("Bearer ") else None
        if not token:
            return jsonify({"error": "Missing Authorization header"}), 401
        try:
            decoded = fb_auth.verify_id_token(token)
        except Exception:
            return jsonify({"error": "Invalid or expired session, please log in again"}), 401
        request.uid = decoded["uid"]
        return view_func(*args, **kwargs)
    return wrapped


def _user_doc_ref(uid):
    return fs_db.collection("user_state").document(uid)


def get_session_context(uid):
    snap = _user_doc_ref(uid).get()
    data = snap.to_dict() or {}
    ctx = dict(DEFAULT_SESSION_CONTEXT)
    ctx.update(data.get("session_context", {}))
    return ctx


def update_session_context(uid, updates):
    ctx = get_session_context(uid)
    ctx.update(updates)
    _user_doc_ref(uid).set({"session_context": ctx}, merge=True)


def get_staged_files_meta(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT id, filename, source, title FROM user_staged_files WHERE user_uid = :p_uid ORDER BY created_at",
        {"p_uid": uid}
    )
    rows = _fetchall(cur)
    conn.close()
    return rows


def add_staged_file_meta(uid, filename, source, title, data_bytes):
    conn = get_db()
    cur = conn.cursor()
    cur.setinputsizes(file_blob=oracledb.DB_TYPE_BLOB)
    cur.execute(
        """INSERT INTO user_staged_files (user_uid, filename, source, title, file_blob)
           VALUES (:p_uid, :filename, :source, :title, :file_blob)""",
        {"p_uid": uid, "filename": filename, "source": source, "title": title, "file_blob": data_bytes}
    )
    conn.commit()
    conn.close()


def clear_staged_files_meta(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute("DELETE FROM user_staged_files WHERE user_uid = :p_uid", {"p_uid": uid})
    cur.execute("DELETE FROM user_vector_chunks WHERE user_uid = :p_uid", {"p_uid": uid})
    conn.commit()
    conn.close()


def remove_staged_file_meta(uid, filename):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "DELETE FROM user_staged_files WHERE user_uid = :p_uid AND filename = :filename",
        {"p_uid": uid, "filename": filename}
    )
    removed = cur.rowcount
    conn.commit()
    conn.close()
    return removed


def get_staged_file_blobs(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT filename, file_blob FROM user_staged_files WHERE user_uid = :p_uid ORDER BY created_at",
        {"p_uid": uid}
    )
    rows = _fetchall(cur)
    conn.close()
    return [(r["filename"], r["file_blob"]) for r in rows]


def get_user_vector_store(uid):
    if uid in _vector_store_cache:
        return _vector_store_cache[uid]

    conn = get_db()
    cur = conn.cursor()
    cur.execute("SELECT chunks_clob FROM user_vector_chunks WHERE user_uid = :p_uid", {"p_uid": uid})
    row = _fetchone(cur)
    conn.close()

    if not row or not row["chunks_clob"]:
        return None

    chunks = json.loads(row["chunks_clob"])
    store = get_vector_store(chunks)
    _vector_store_cache[uid] = store
    return store


def set_user_vector_store(uid, store, chunks):
    _vector_store_cache[uid] = store
    chunks_json = json.dumps(chunks)

    conn = get_db()
    cur = conn.cursor()
    cur.setinputsizes(p_uid=None, chunks_clob=oracledb.DB_TYPE_CLOB)
    cur.execute(
        """MERGE INTO user_vector_chunks uvc
           USING (SELECT :p_uid AS user_uid FROM DUAL) src
           ON (uvc.user_uid = src.user_uid)
           WHEN MATCHED THEN UPDATE SET
               uvc.chunks_clob = :chunks_clob,
               uvc.updated_at  = CURRENT_TIMESTAMP
           WHEN NOT MATCHED THEN INSERT (user_uid, chunks_clob)
               VALUES (:p_uid, :chunks_clob)""",
        {"p_uid": uid, "chunks_clob": chunks_json}
    )
    conn.commit()
    conn.close()


def get_pdf_text(pdf_files):
    text = ""
    for pdf in pdf_files:
        pdf_reader = PdfReader(pdf)
        for page in pdf_reader.pages:
            content = page.extract_text()
            if content:
                text += content
    return text


def get_text_chunks(text):
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    return text_splitter.split_text(text)


def get_vector_store(text_chunks):
    embeddings = HuggingFaceEndpointEmbeddings(
        huggingfacehub_api_token=os.getenv("HUGGINGFACE_API_TOKEN"),
        repo_id="sentence-transformers/all-MiniLM-L6-v2"
    )
    store = FAISS.from_texts(text_chunks, embedding=embeddings)
    return store


def get_conversational_chain(bloom_level, outcomes, weightage, language, study_mode="normal", vibe_type="default"):

    base_instruction = """
    You are an academic tutor. Answer the question based on the provided context,
    keeping the learner's Goal, Cognitive Level, and Topic Weightage in mind.
    """

    if study_mode == "professor":
        language = "English"
        mode_instruction = """
        PROFESSOR MODE: Provide highly technical, academically rigorous answers.
        Use formal academic language, include technical terminology, cite concepts precisely,
        and structure answers as a professor would in an exam setting.
        Focus on conceptual clarity, theoretical depth, and exam-oriented explanations.
        Include relevant formulas, theorems, or technical details where applicable.
        """
    elif study_mode == "vibe":
        if vibe_type == "mumbai":
            language = "Hinglish (Mumbai slang)"
            mode_instruction = """
            MUMBAI CHA BHAI MODE: Talk like a cool Mumbai friend explaining concepts.
            Use Mumbai slang naturally - words like 'bhai', 'bhidu', 'ekdum', 'bindaas',
            'mast', 'apun', 'tapri', 'cutting', 'funda', 'scene', etc.
            Keep it casual but informative. Make learning fun and relatable like a friend
            teaching another friend. Example: "Arre bhidu, yeh concept ekdum simple hai..."
            """
        elif vibe_type == "hyderabadi":
            language = "Hinglish (Hyderabadi slang)"
            mode_instruction = """
            HYDERABADI MIA MODE: Explain concepts in Hyderabadi style.
            Use Hyderabadi slang naturally - words like 'mia', 'nakko', 'hau', 'kya baat hai',
            'baigan', 'potti', 'kiraak', 'scene kya hai', 'dimaag ka dahi', etc.
            Keep it friendly and conversational. Example: "Arre mia, yeh topic toh ekdum kiraak hai..."
            """
        elif vibe_type == "punjabi":
            language = "Hinglish (Punjabi slang)"
            mode_instruction = """
            PUNJAB DA PUTTAR MODE: Explain concepts in energetic Punjabi style.
            Use Punjabi slang naturally - words like 'veer', 'paaji', 'yaar', 'oye', 'chak de',
            'kiddan', 'sohneyo', 'balle balle', 'vadiya', 'chakkar', 'fatte chak', 'jhakaas',
            'ghaint', 'kamaal', 'pappe', etc.
            Keep it enthusiastic and brotherly. Example: "Oye paaji, yeh concept toh bilkul vadiya hai,
            chak de phatte saari theory..."
            """
        else:
            language = "Hinglish"
            mode_instruction = """
            HINGLISH MODE: Explain in a mix of Hindi and English (Hinglish).
            Use casual, friendly language that Indians commonly use.
            Mix Hindi and English naturally like friends talking.
            Example: "Dekho, yeh concept basically yeh hai ki..."
            """
    else:
        mode_instruction = """
        NORMAL MODE: Provide clear, comprehensive answers in the user's preferred language.
        Balance between being informative and accessible.
        """

    prompt_template = f"""
    {base_instruction}

    {mode_instruction}

    Learner's Course Outcomes: {outcomes}
    Target Bloom's Taxonomy Level: {bloom_level}
    Topic Weightage in Exam: {weightage} marks
    Response Language/Style: {language}

    Instructions:
    1. Use the provided context to answer.
    2. Adjust your explanation style to match the Bloom's Level (e.g., 'Analyze' should compare/contrast, 'Remember' should define).
    3. For higher weightage topics ({weightage} marks), provide more comprehensive explanations with examples and detailed coverage.
    4. For lower weightage topics, keep explanations concise but complete.
    5. If the answer is not in the context, say: "I can't find the answer in the notes."
    6. It's an Indian College Exam, so be extra careful about the content. Indian professors love detailed content.
    7. Maintain the specified language/style consistently throughout your response.

    Context:
    {{context}}

    Question:
    {{question}}

    Answer:
    """

    model = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        google_api_key=api_key,
        temperature=0.3
    )
    prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
    return load_qa_chain(model, chain_type="stuff", prompt=prompt)


@app.route('/')
def dashboard():
    return render_template('dashboard.html')


@app.route('/dashboard')
def dashboard_alias():
    return render_template('dashboard.html')


@app.route('/chat')
def chat():
    return render_template('chat.html')


@app.route('/tests')
def tests():
    return render_template('tests.html')


@app.route('/evaluate')
def evaluate():
    return render_template('evaluate.html')


@app.route('/roadmap')
def roadmap():
    return render_template('roadmap.html')


def admin_required(view_func):
    @wraps(view_func)
    def wrapped(*args, **kwargs):
        if not session.get("is_admin"):
            if request.path.startswith("/admin/api/"):
                return jsonify({"error": "Unauthorized"}), 401
            return redirect(url_for("admin_login_page"))
        return view_func(*args, **kwargs)
    return wrapped


@app.route('/admin/login')
def admin_login_page():
    if session.get("is_admin"):
        return redirect(url_for("admin_dashboard_page"))
    return render_template('admin-login.html')


@app.route('/admin/api/login', methods=['POST'])
def admin_api_login():
    data = request.json or {}
    username = data.get("username", "")
    password = data.get("password", "")

    if username == ADMIN_USERNAME and password == ADMIN_PASSWORD:
        session["is_admin"] = True
        return jsonify({"message": "Logged in"})

    return jsonify({"error": "Invalid username or password"}), 401


@app.route('/admin/api/logout', methods=['POST'])
def admin_api_logout():
    session.pop("is_admin", None)
    return jsonify({"message": "Logged out"})


@app.route('/admin/dashboard')
@admin_required
def admin_dashboard_page():
    return render_template('admin-dashboard.html')


@app.route('/signup')
def signup():
    return render_template('signup.html')


@app.route('/profile')
def profile_page():
    return render_template('profile.html')


@app.route('/competency-test')
def competency_test_page():
    return render_template('competency-test.html')


@app.route('/report')
def report_page():
    return render_template('report.html')


@app.route('/login')
def login():
    return render_template('login.html')


@app.route('/terms')
def terms():
    return render_template('terms.html')


@app.route("/static/js/firebase-config.js")
def firebase_config_js():
    js = f"""
    const firebaseConfig = {{
        apiKey: "{os.environ['FIREBASE_API_KEY']}",
        authDomain: "{os.environ['FIREBASE_AUTH_DOMAIN']}",
        projectId: "{os.environ['FIREBASE_PROJECT_ID']}",
        storageBucket: "{os.environ.get('FIREBASE_STORAGE_BUCKET', '')}",
        messagingSenderId: "{os.environ['FIREBASE_MESSAGING_SENDER_ID']}",
        appId: "{os.environ['FIREBASE_APP_ID']}",
        measurementId: "{os.environ.get('FIREBASE_MEASUREMENT_ID', '')}"
    }};

    if (!firebase.apps.length) {{
        firebase.initializeApp(firebaseConfig);
    }}
    const auth = firebase.auth();

    async function authFetch(url, options = {{}}) {{
        const user = firebase.auth().currentUser;
        if (!user) {{
            throw new Error("Not signed in");
        }}
        const token = await user.getIdToken();
        const headers = Object.assign({{}}, options.headers, {{
            "Authorization": "Bearer " + token
        }});
        return fetch(url, Object.assign({{}}, options, {{ headers }}));
    }}
    """
    return Response(js, mimetype="application/javascript")


@app.route('/api/books', methods=['GET'])
def api_books():
    return jsonify(PREUPLOADED_BOOKS)


@app.route('/upload_stage', methods=['POST'])
@require_uid
def upload_stage():
    uid = request.uid
    files = request.files.getlist("pdf_files")
    if not files or files[0].filename == '':
        return jsonify({"error": "No files received"}), 400

    added = []
    for f in files:
        data_bytes = f.read()
        add_staged_file_meta(uid, f.filename, "upload", f.filename, data_bytes)
        added.append(f.filename)

    return jsonify({"message": f"{len(added)} file(s) added to your notes", "files": added})


@app.route('/select_book', methods=['POST'])
@require_uid
def select_book():
    uid = request.uid
    data = request.json or {}
    book_id = data.get("book_id")
    book = next((b for b in PREUPLOADED_BOOKS if b["id"] == book_id), None)
    if not book:
        return jsonify({"error": "Book not found"}), 404

    path = os.path.join(BOOKS_DIR, book["filename"])
    if not os.path.exists(path):
        return jsonify({
            "error": f"'{book['title']}' isn't available on the server yet. Please contact your admin."
        }), 404

    with open(path, "rb") as fh:
        data_bytes = fh.read()

    add_staged_file_meta(uid, book["filename"], "book", book["title"], data_bytes)

    return jsonify({
        "message": f"'{book['title']}' added to your notes",
        "title": book["title"],
        "filename": book["filename"]
    })


@app.route('/api/save_profile', methods=['POST'])
def save_profile():
    data = request.json or {}
    uid = data.get("uid")
    if not uid:
        return jsonify({"error": "Missing uid"}), 400

    name = (data.get("name") or "").strip()
    email = (data.get("email") or "").strip()
    if not name or not email:
        return jsonify({"error": "Name and email are required"}), 400

    age = data.get("age")
    phone = data.get("phone", "")
    department = data.get("department", "")
    designation = data.get("designation", "")
    education = data.get("education", [])
    skills = data.get("skills", [])
    experience = data.get("experience", [])

    if not skills:
        return jsonify({"error": "Please add at least one skill"}), 400

    conn = get_db()
    cur = conn.cursor()

    cur.execute('SELECT id FROM users WHERE "UID" = :1', (uid,))
    existing = _fetchone(cur)
    if existing:
        user_id = existing["id"]
        cur.execute(
            """UPDATE users SET name=:1, age=:2, phone=:3, email=:4, department=:5, designation=:6
               WHERE id=:7""",
            (name, age, phone, email, department, designation, user_id)
        )
        cur.execute("DELETE FROM user_education WHERE user_id = :1", (user_id,))
        cur.execute("DELETE FROM user_skills WHERE user_id = :1", (user_id,))
        cur.execute("DELETE FROM user_experience WHERE user_id = :1", (user_id,))
    else:
        id_var = cur.var(oracledb.NUMBER)
        cur.execute(
            """INSERT INTO users ("UID", name, age, phone, email, department, designation)
               VALUES (:1, :2, :3, :4, :5, :6, :7) RETURNING id INTO :8""",
            (uid, name, age, phone, email, department, designation, id_var)
        )
        user_id = _getid(id_var)

    for edu in education:
        if not (edu.get("degree") or edu.get("institution")):
            continue
        cur.execute(
            "INSERT INTO user_education (user_id, degree, institution, year) VALUES (:1, :2, :3, :4)",
            (user_id, edu.get("degree", ""), edu.get("institution", ""), edu.get("year", ""))
        )

    for skill in skills:
        if not skill.get("name"):
            continue
        cur.execute(
            "INSERT INTO user_skills (user_id, skill_name, self_rated_level) VALUES (:1, :2, :3)",
            (user_id, skill["name"], skill.get("level", "Beginner"))
        )

    for exp in experience:
        if not (exp.get("role") or exp.get("organization")):
            continue
        cur.execute(
            """INSERT INTO user_experience (user_id, role, organization, duration, description)
               VALUES (:1, :2, :3, :4, :5)""",
            (user_id, exp.get("role", ""), exp.get("organization", ""), exp.get("duration", ""), exp.get("description", ""))
        )

    conn.commit()
    conn.close()

    return jsonify({"message": "Profile saved!", "user_id": user_id})


@app.route('/api/profile/<uid>', methods=['GET'])
def get_profile(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found"}), 404

    cur.execute(
        "SELECT id, skill_name, self_rated_level FROM user_skills WHERE user_id = :1", (user["id"],)
    )
    skills = _fetchall(cur)
    cur.execute(
        "SELECT degree, institution, year FROM user_education WHERE user_id = :1", (user["id"],)
    )
    education = _fetchall(cur)
    cur.execute(
        "SELECT role, organization, duration, description FROM user_experience WHERE user_id = :1", (user["id"],)
    )
    experience = _fetchall(cur)
    conn.close()

    return jsonify({
        "name": user["name"], "age": user["age"], "phone": user["phone"], "email": user["email"],
        "department": user["department"], "designation": user["designation"],
        "skills": skills,
        "education": education,
        "experience": experience,
    })


@app.route('/api/profile/<uid>/skills', methods=['POST'])
def add_profile_skill(uid):
    data = request.json or {}
    name = (data.get("name") or "").strip()
    level = data.get("level", "Beginner")

    if not name:
        return jsonify({"error": "Skill name is required"}), 400

    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT id FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found"}), 404

    cur.execute(
        "SELECT id FROM user_skills WHERE user_id = :1 AND LOWER(skill_name) = LOWER(:2)",
        (user["id"], name)
    )
    existing = _fetchone(cur)
    if existing:
        conn.close()
        return jsonify({"error": "That skill is already on your profile"}), 400

    id_var = cur.var(oracledb.NUMBER)
    cur.execute(
        "INSERT INTO user_skills (user_id, skill_name, self_rated_level) VALUES (:1, :2, :3) RETURNING id INTO :4",
        (user["id"], name, level, id_var)
    )
    skill_id = _getid(id_var)
    conn.commit()
    conn.close()

    return jsonify({"id": skill_id, "skill_name": name, "self_rated_level": level})


@app.route('/api/profile/<uid>/skills/<int:skill_id>', methods=['DELETE'])
def remove_profile_skill(uid, skill_id):
    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT id FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found"}), 404

    cur.execute("DELETE FROM user_skills WHERE id = :1 AND user_id = :2", (skill_id, user["id"]))
    deleted = cur.rowcount
    conn.commit()
    conn.close()

    if not deleted:
        return jsonify({"error": "Skill not found"}), 404

    return jsonify({"message": "Skill removed"})


@app.route('/processed_status', methods=['GET'])
@require_uid
def processed_status():
    conn = get_db()
    cur = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM user_vector_chunks WHERE user_uid = :p_uid", {"p_uid": request.uid})
    count = cur.fetchone()[0]
    conn.close()
    return jsonify({"processed": count > 0})


@app.route('/staged_files', methods=['GET'])
@require_uid
def get_staged_files():
    files = get_staged_files_meta(request.uid)
    return jsonify([
        {"filename": f["filename"], "source": f["source"], "title": f.get("title", f["filename"])}
        for f in files
    ])


@app.route('/staged_files', methods=['DELETE'])
@require_uid
def clear_staged_files():
    clear_staged_files_meta(request.uid)
    _vector_store_cache.pop(request.uid, None)
    return jsonify({"message": "cleared"})


@app.route('/staged_files/<path:filename>', methods=['DELETE'])
@require_uid
def remove_staged_file(filename):
    removed = remove_staged_file_meta(request.uid, filename)
    return jsonify({"message": "removed" if removed else "not found", "removed": removed > 0})


@app.route('/update_settings', methods=['POST'])
@require_uid
def update_settings():
    data = request.json or {}
    yt_url = data.get("yt_url", "")
    outcomes = data.get("course_outcomes", "")
    bloom_index = data.get("bloom_level", "2")
    weightage = data.get("weightage", "4")
    language = data.get("language", "")

    bloom_map = {
        "1": "Remember (Define, list, memorize)",
        "2": "Understand (Explain, classify, discuss)",
        "3": "Apply (Solve, use, implement)",
        "4": "Analyze (Compare, contrast, examine)",
        "5": "Evaluate (Argue, judge, critique)",
        "6": "Create (Design, construct, develop)"
    }

    update_session_context(request.uid, {
        "course_outcomes": outcomes,
        "bloom_level": bloom_map.get(bloom_index, "Understand"),
        "weightage": weightage,
        "language": language,
        "yt_url": yt_url,
    })

    return jsonify({"message": "Settings updated!"})


@app.route('/process', methods=['POST'])
@require_uid
def process_content():
    uid = request.uid
    staged = get_staged_file_blobs(uid)

    if not staged:
        return jsonify({
            "error": "No notes to process yet. Upload notes or pick a book first."
        }), 400

    raw_text = ""
    for filename, data_bytes in staged:
        pdf_reader = PdfReader(io.BytesIO(data_bytes))
        for page in pdf_reader.pages:
            content = page.extract_text()
            if content:
                raw_text += content

    ctx = get_session_context(uid)
    yt_url = ctx.get("yt_url", "")
    if yt_url:
        raw_text += f"\nNote: User also provided a YouTube lecture at {yt_url}."

    text_chunks = get_text_chunks(raw_text)
    store = get_vector_store(text_chunks)
    set_user_vector_store(uid, store, text_chunks)

    return jsonify({"message": f"Content processed at {ctx['bloom_level']} level!"})


VALID_DIFFICULTIES = ("easy", "medium", "hard")
VALID_QUESTION_COUNTS = (10, 20, 30, 40, 50)

DIFFICULTY_GUIDES = {
    "easy": "Basic recall and definition-level questions (Bloom's Remember/Understand level). Keep wording simple and direct.",
    "medium": "Applied, comparison, and scenario-based questions (Bloom's Apply/Analyze level).",
    "hard": "Deep analytical, evaluative, multi-concept questions that require connecting ideas (Bloom's Analyze/Evaluate/Create level)."
}


def _clean_json_response(raw_text):
    cleaned = raw_text.strip()
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", cleaned, flags=re.MULTILINE)
    return cleaned.strip()


def _looks_like_front_matter(text):
    lowered = text.lower()

    strong_markers = [
        "new to this edition", "changes in this edition", "changes to this edition",
        "what's new in this edition", "revised in this edition",
        "fourth edition", "third edition", "second edition", "fifth edition",
        "sixth edition", "seventh edition", "eighth edition", "ninth edition",
        "how to use this book", "organization of this book", "organization of the book",
        "practice set", "review questions", "review question",
        "end-of-chapter", "end of chapter", "supplementary material",
        "instructor's manual", "instructor resources", "companion website",
        "solutions manual", "study guide", "learning objectives for this chapter",
        "chapter summary", "chapter outline", "about this book",
    ]
    if any(marker in lowered for marker in strong_markers):
        return True

    weak_markers = [
        "isbn", "copyright ©", "all rights reserved", "printed in",
        "library of congress", "about the author", "acknowledgments",
        "acknowledgements", "preface", "table of contents",
        "publisher", "published by", "www.",
        "trademark", "no part of this publication"
    ]
    hits = sum(1 for marker in weak_markers if marker in lowered)
    return hits >= 2


def _gather_test_context(store, num_questions):
    seed_queries = [
        "definitions and key concepts explained",
        "how a process, mechanism, or algorithm works step by step",
        "real-world examples and applications",
        "comparison or difference between two or more types, methods, or approaches",
        "advantages, disadvantages, and limitations",
        "important techniques, models, or structures and their uses",
    ]

    k_per_query = max(4, min(10, (num_questions // len(seed_queries)) + 3))

    seen = set()
    good_docs = []
    for query in seed_queries:
        for doc in store.similarity_search(query, k=k_per_query):
            key = doc.page_content[:120]
            if key in seen:
                continue
            seen.add(key)
            if _looks_like_front_matter(doc.page_content):
                continue
            good_docs.append(doc)

    return "\n\n".join(doc.page_content for doc in good_docs)


def _generate_questions_from_notes(uid, difficulty, num_questions):
    store = get_user_vector_store(uid)
    if store is None:
        return None, ("Please process your notes first from the Dashboard.", 400)

    context = _gather_test_context(store, num_questions)

    if not context.strip():
        return None, ("Couldn't find enough usable content in your notes to build a test.", 400)

    generation_target = num_questions + max(3, num_questions // 3)

    prompt = f"""
    You are an exam-setter creating a multiple choice question (MCQ) test for Indian college
    students, based ONLY on the SUBJECT MATTER in the context below.

    Difficulty: {difficulty.upper()} — {DIFFICULTY_GUIDES[difficulty]}
    Number of questions to generate: {generation_target}

    STRICT RULES — read carefully:
    1. Test the SUBJECT CONTENT only — concepts, definitions, processes, comparisons,
       applications, examples, advantages/disadvantages, cause-and-effect, classifications.
    2. NEVER ask about the book itself or how it is packaged/organized/taught from. This
       includes (but is not limited to) questions like:
       - "What is the primary purpose of 'Review questions' in a practice set?"
       - "What do 'Exercises' in a practice set typically require from the student?"
       - "What significant change was made to Chapter 8 in the Fourth Edition?"
       - anything about the author, publisher, title, edition, ISBN, chapter/page numbers,
         table of contents, preface, "review questions", "exercises", "practice sets",
         "learning objectives", or "according to the book/author...".
       If a piece of context is about the book's structure, pedagogy, or publishing history
       rather than the actual subject, IGNORE that piece of context entirely — do not
       write a question from it, even a "quick"/"easy" one.
    3. Write questions the way a professor would ask them in a real subject exam, for example:
       - "Which of the following is NOT a system call?"
       - "Where can ring topology be used?"
       - "Which of the following is not an application of reinforcement learning?"
       - "What is the primary purpose of X?" — where X is a real technical concept
         (e.g. "a semaphore", "a firewall", "normalization"), never a book section.
       - "Which technique is best suited for Y?"
       Mix straightforward "what is / which of these" questions with a good number of
       negative-form questions ("which of the following is NOT...", "all of the following
       EXCEPT...") and applied/scenario questions, matching the {difficulty} difficulty.
    4. All 4 options must be plausible and in the same category as each other (e.g. don't
       mix a real system call with three obviously made-up words) so the question actually
       requires understanding, not guessing by elimination.
    5. For EACH question, also give a short topic tag (2-4 words) naming the specific
       technical concept being tested (e.g. "System Calls", "Ring Topology", "Reinforcement
       Learning Applications") — never use the book title, "General", or "Chapter 1" as
       the topic.
    6. Before finalizing each question, double-check: could this question be answered by
       someone who has never read this material but knows how textbooks are structured?
       If yes, discard it and write a different question about the actual subject instead.

    Return ONLY a valid JSON array (no markdown fences, no commentary) where every item has
    exactly this shape:
    {{
      "topic": "short topic name",
      "question": "the question text",
      "options": {{"a": "...", "b": "...", "c": "...", "d": "..."}},
      "correct_option": "a",
      "explanation": "1-2 sentence explanation of why the correct answer is correct"
    }}

    Context:
    {context}
    """

    try:
        model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=api_key, temperature=0.5)
        response = model.invoke(prompt)
        questions = json.loads(_clean_json_response(response.content))
    except Exception as e:
        print(f"Error generating test: {str(e)}")
        return None, ("Failed to generate the test. Please try again.", 500)

    banned_phrases = (
        "author", "publisher", "isbn", "the book", "this book", "edition",
        "table of contents", "practice set", "review question", "exercises",
        "exercise", "chapter", "preface", "instructor", "workbook",
        "study guide", "companion website", "supplementary material",
        "learning objective", "appendix"
    )
    questions = [
        q for q in questions
        if isinstance(q.get("question"), str)
        and not any(phrase in q["question"].lower() for phrase in banned_phrases)
    ]

    if not questions:
        return None, ("Generated questions didn't pass quality checks. Please try again.", 500)

    questions = questions[:num_questions]

    staged = get_staged_files_meta(uid)
    source_title = ", ".join(sorted({f.get("title", f["filename"]) for f in staged})) or "Uploaded Notes"

    conn = get_db()
    cur = conn.cursor()
    id_var = cur.var(oracledb.NUMBER)
    cur.execute(
        "INSERT INTO tests (difficulty, num_questions, source_title) VALUES (:1, :2, :3) RETURNING id INTO :4",
        (difficulty, len(questions), source_title, id_var)
    )
    test_id = _getid(id_var)

    saved_questions = []
    for i, q in enumerate(questions):
        try:
            options = q["options"]
            qid_var = cur.var(oracledb.NUMBER)
            cur.execute(
                """INSERT INTO questions
                   (topic, difficulty, question_text, option_a, option_b, option_c, option_d,
                    correct_option, explanation, source_title)
                   VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10) RETURNING id INTO :11""",
                (
                    q.get("topic", "General"), difficulty, q["question"],
                    options["a"], options["b"], options["c"], options["d"],
                    q["correct_option"], q.get("explanation", ""), source_title, qid_var
                )
            )
            question_id = _getid(qid_var)
            cur.execute(
                "INSERT INTO test_questions (test_id, question_id, question_order) VALUES (:1, :2, :3)",
                (test_id, question_id, i)
            )
            saved_questions.append({
                "id": question_id,
                "topic": q.get("topic", "General"),
                "question": q["question"],
                "options": options,
                "correct_option": q["correct_option"],
                "explanation": q.get("explanation", "")
            })
        except (KeyError, TypeError):
            continue

    conn.commit()
    conn.close()

    return {
        "test_id": test_id,
        "difficulty": difficulty,
        "source_title": source_title,
        "questions": saved_questions
    }, None


def _generate_test_from_bank(difficulty, num_questions):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT * FROM questions WHERE difficulty = :1 ORDER BY dbms_random.value FETCH FIRST :2 ROWS ONLY",
        (difficulty, num_questions)
    )
    rows = _fetchall(cur)

    if not rows:
        conn.close()
        return None, (
            f"No stored {difficulty} questions in the bank yet. "
            "Generate a test from notes first to build up the bank.", 400
        )

    id_var = cur.var(oracledb.NUMBER)
    cur.execute(
        "INSERT INTO tests (difficulty, num_questions, source_title) VALUES (:1, :2, :3) RETURNING id INTO :4",
        (difficulty, len(rows), "Question Bank", id_var)
    )
    test_id = _getid(id_var)

    saved_questions = []
    for i, row in enumerate(rows):
        cur.execute(
            "INSERT INTO test_questions (test_id, question_id, question_order) VALUES (:1, :2, :3)",
            (test_id, row["id"], i)
        )
        saved_questions.append({
            "id": row["id"],
            "topic": row["topic"],
            "question": row["question_text"],
            "options": {
                "a": row["option_a"], "b": row["option_b"],
                "c": row["option_c"], "d": row["option_d"]
            },
            "correct_option": row["correct_option"],
            "explanation": row["explanation"]
        })

    conn.commit()
    conn.close()

    return {
        "test_id": test_id,
        "difficulty": difficulty,
        "source_title": "Question Bank",
        "questions": saved_questions
    }, None


@app.route('/generate_test', methods=['POST'])
def generate_test():
    data = request.json or {}
    difficulty = data.get("difficulty", "medium")
    num_questions = data.get("num_questions", 10)
    source = data.get("source", "notes")
    uid = data.get("uid")

    if difficulty not in VALID_DIFFICULTIES:
        difficulty = "medium"
    try:
        num_questions = int(num_questions)
    except (TypeError, ValueError):
        num_questions = 10
    if num_questions not in VALID_QUESTION_COUNTS:
        num_questions = 10

    if source == "bank":
        result, error = _generate_test_from_bank(difficulty, num_questions)
    else:
        if not uid:
            return jsonify({"error": "Missing uid — please sign in again."}), 400
        result, error = _generate_questions_from_notes(uid, difficulty, num_questions)

    if error:
        message, status_code = error
        return jsonify({"error": message}), status_code

    if uid:
        conn = get_db()
        cur = conn.cursor()
        cur.execute('SELECT id FROM users WHERE "UID" = :1', (uid,))
        user = _fetchone(cur)
        if user:
            cur.execute("UPDATE tests SET user_id = :1 WHERE id = :2", (user["id"], result["test_id"]))
            conn.commit()
        conn.close()

    return jsonify(result)


@app.route('/submit_test', methods=['POST'])
def submit_test():
    data = request.json or {}
    test_id = data.get("test_id")
    score = data.get("score")
    total = data.get("total")
    uid = data.get("uid")
    answers = data.get("answers", {})

    if test_id is None or score is None or total is None:
        return jsonify({"error": "Missing test_id, score, or total"}), 400

    conn = get_db()
    cur = conn.cursor()

    user_id = None
    if uid:
        cur.execute('SELECT id FROM users WHERE "UID" = :1', (uid,))
        user = _fetchone(cur)
        if user:
            user_id = user["id"]
            cur.execute("UPDATE tests SET user_id = :1 WHERE id = :2", (user_id, test_id))

    cur.execute(
        "INSERT INTO test_attempts (test_id, score, total, user_id) VALUES (:1, :2, :3, :4)",
        (test_id, score, total, user_id)
    )

    for question_id, selected_option in answers.items():
        cur.execute(
            "INSERT INTO user_answers (test_id, question_id, selected_option) VALUES (:1, :2, :3)",
            (test_id, int(question_id), selected_option)
        )

    conn.commit()
    conn.close()

    if user_id:
        _update_skill_competency_and_progress(user_id, test_id)

    return jsonify({"message": "Result saved!"})


@app.route('/questions_bank', methods=['GET'])
def questions_bank():
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT topic, difficulty, COUNT(*) as count FROM questions GROUP BY topic, difficulty ORDER BY topic"
    )
    rows = _fetchall(cur)
    conn.close()
    return jsonify(rows)


SKILL_TEST_TOTAL_QUESTIONS = 20


def _skill_test_distribution(total):
    easy = round(total * 0.5)
    medium = round(total * 0.25)
    hard = total - easy - medium
    return easy, medium, hard


def _generate_skill_questions(skills, easy_count, medium_count, hard_count):
    skill_names = [s["name"].strip() for s in skills if s.get("name", "").strip()]
    if not skill_names:
        return None, ("No skills to test.", 400)

    total = easy_count + medium_count + hard_count
    skills_list_str = ", ".join(skill_names)

    prompt = f"""
    You are an examiner creating an initial competency assessment MCQ test for a new employee,
    covering the following self-declared skills: {skills_list_str}.

    Generate EXACTLY {total} multiple choice questions:
    - {easy_count} EASY questions (basic recall/definition-level, Bloom's Remember/Understand)
    - {medium_count} MEDIUM questions (applied/comparison-level, Bloom's Apply/Analyze)
    - {hard_count} HARD questions (deep analytical/scenario-level, Bloom's Analyze/Evaluate)

    Spread the questions across ALL the listed skills as evenly as possible — don't test only
    one or two skills. Each question must test real, practical knowledge of one of the listed
    skills: concepts, syntax, best practices, real-world usage, common pitfalls, or comparisons
    between tools/techniques within that skill.

    STRICT RULES:
    1. Never ask about this test, this platform, or any meta-topic — only real technical or
       professional knowledge of the named skills.
    2. Write questions the way a real interviewer/examiner would, e.g.:
       - "Which of the following is NOT a valid way to handle exceptions in Python?"
       - "Which SQL clause is used to filter grouped results?"
       - "Which of the following is not a principle of good UX design?"
       Mix straightforward and negative-form ("NOT", "EXCEPT") questions.
    3. All 4 options must be plausible and in the same category, so the question requires real
       understanding rather than guessing by elimination.
    4. The "topic" field for each question MUST be exactly one of these skill names:
       {skill_names}. Pick whichever skill the question actually tests.
    5. Include a "difficulty" field for each question — exactly one of: "easy", "medium", "hard".

    Return ONLY a valid JSON array (no markdown fences, no commentary) where every item has
    exactly this shape:
    {{
      "topic": "one of the exact skill names above",
      "difficulty": "easy" | "medium" | "hard",
      "question": "the question text",
      "options": {{"a": "...", "b": "...", "c": "...", "d": "..."}},
      "correct_option": "a",
      "explanation": "1-2 sentence explanation of why the correct answer is correct"
    }}
    """

    try:
        model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=api_key, temperature=0.5)
        response = model.invoke(prompt)
        questions = json.loads(_clean_json_response(response.content))
    except Exception as e:
        print(f"Error generating skill test: {str(e)}")
        return None, ("Failed to generate the skill assessment. Please try again.", 500)

    banned_phrases = ("this test", "this platform", "this assessment", "the app", "blitzlearn")
    cleaned = [
        q for q in questions
        if isinstance(q.get("question"), str)
        and not any(p in q["question"].lower() for p in banned_phrases)
        and q.get("difficulty") in ("easy", "medium", "hard")
        and q.get("topic")
    ]

    if not cleaned:
        return None, ("Generated questions didn't pass quality checks. Please try again.", 500)

    return cleaned, None


@app.route('/generate_skill_test', methods=['POST'])
def generate_skill_test():
    data = request.json or {}
    uid = data.get("uid")
    if not uid:
        return jsonify({"error": "Missing uid"}), 400

    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found. Please complete signup first."}), 404

    cur.execute(
        "SELECT skill_name, self_rated_level FROM user_skills WHERE user_id = :1", (user["id"],)
    )
    skill_rows = _fetchall(cur)
    skills = [{"name": r["skill_name"], "level": r["self_rated_level"]} for r in skill_rows]

    if not skills:
        conn.close()
        return jsonify({"error": "No skills found on your profile."}), 400

    easy_count, medium_count, hard_count = _skill_test_distribution(SKILL_TEST_TOTAL_QUESTIONS)
    questions, error = _generate_skill_questions(skills, easy_count, medium_count, hard_count)

    if error:
        conn.close()
        message, status_code = error
        return jsonify({"error": message}), status_code

    id_var = cur.var(oracledb.NUMBER)
    cur.execute(
        "INSERT INTO tests (difficulty, num_questions, source_title, user_id) VALUES (:1, :2, :3, :4) RETURNING id INTO :5",
        ("mixed", len(questions), "Initial Skill Assessment", user["id"], id_var)
    )
    test_id = _getid(id_var)

    saved_questions = []
    for i, q in enumerate(questions):
        try:
            options = q["options"]
            qid_var = cur.var(oracledb.NUMBER)
            cur.execute(
                """INSERT INTO questions
                   (topic, difficulty, question_text, option_a, option_b, option_c, option_d,
                    correct_option, explanation, source_title)
                   VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10) RETURNING id INTO :11""",
                (
                    q["topic"], q["difficulty"], q["question"],
                    options["a"], options["b"], options["c"], options["d"],
                    q["correct_option"], q.get("explanation", ""), "Initial Skill Assessment", qid_var
                )
            )
            question_id = _getid(qid_var)
            cur.execute(
                "INSERT INTO test_questions (test_id, question_id, question_order) VALUES (:1, :2, :3)",
                (test_id, question_id, i)
            )
            saved_questions.append({
                "id": question_id,
                "topic": q["topic"],
                "difficulty": q["difficulty"],
                "question": q["question"],
                "options": options,
                "correct_option": q["correct_option"],
                "explanation": q.get("explanation", "")
            })
        except (KeyError, TypeError):
            continue

    conn.commit()
    conn.close()

    if not saved_questions:
        return jsonify({"error": "Failed to generate a usable skill assessment. Please try again."}), 500

    return jsonify({
        "test_id": test_id,
        "skills": [s["name"] for s in skills],
        "questions": saved_questions
    })


def _proficiency_label(percent):
    if percent >= 80:
        return "Advanced"
    if percent >= 50:
        return "Intermediate"
    return "Beginner"


@app.route('/submit_skill_test', methods=['POST'])
def submit_skill_test():
    data = request.json or {}
    uid = data.get("uid")
    test_id = data.get("test_id")
    answers = data.get("answers", {})

    if not uid or not test_id:
        return jsonify({"error": "Missing uid or test_id"}), 400

    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found."}), 404

    cur.execute(
        """SELECT q.id, q.topic, q.difficulty, q.correct_option
           FROM test_questions tq
           JOIN questions q ON q.id = tq.question_id
           WHERE tq.test_id = :1
           ORDER BY tq.question_order""",
        (test_id,)
    )
    rows = _fetchall(cur)

    if not rows:
        conn.close()
        return jsonify({"error": "Test not found."}), 404

    skill_stats = {}
    overall_correct = 0

    for row in rows:
        topic = row["topic"] or "General"
        skill_stats.setdefault(topic, {"correct": 0, "total": 0})
        skill_stats[topic]["total"] += 1

        selected = answers.get(str(row["id"]))
        if selected == row["correct_option"]:
            skill_stats[topic]["correct"] += 1
            overall_correct += 1

    overall_total = len(rows)

    skills_breakdown = []
    for topic, stats in skill_stats.items():
        percent = round((stats["correct"] / stats["total"]) * 100) if stats["total"] else 0
        skills_breakdown.append({
            "skill": topic,
            "correct": stats["correct"],
            "total": stats["total"],
            "percent": percent,
            "level": _proficiency_label(percent)
        })
    skills_breakdown.sort(key=lambda s: s["percent"])

    cur.execute(
        "INSERT INTO test_attempts (test_id, score, total, user_id) VALUES (:1, :2, :3, :4)",
        (test_id, overall_correct, overall_total, user["id"])
    )

    for row in rows:
        selected = answers.get(str(row["id"]))
        cur.execute(
            "INSERT INTO user_answers (test_id, question_id, selected_option) VALUES (:1, :2, :3)",
            (test_id, row["id"], selected)
        )

    id_var = cur.var(oracledb.NUMBER)
    cur.execute(
        """INSERT INTO skill_reports (user_id, test_id, overall_score, overall_total, skills_breakdown)
           VALUES (:1, :2, :3, :4, :5) RETURNING id INTO :6""",
        (user["id"], test_id, overall_correct, overall_total, json.dumps(skills_breakdown), id_var)
    )
    report_id = _getid(id_var)
    conn.commit()
    conn.close()

    _update_skill_competency_and_progress(user["id"], test_id)

    return jsonify({
        "report_id": report_id,
        "overall_score": overall_correct,
        "overall_total": overall_total,
        "skills": skills_breakdown
    })


@app.route('/api/skill_report/<uid>', methods=['GET'])
def get_latest_skill_report(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    if not user:
        conn.close()
        return jsonify({"error": "Profile not found."}), 404

    cur.execute(
        "SELECT * FROM skill_reports WHERE user_id = :1 ORDER BY generated_at DESC FETCH FIRST 1 ROWS ONLY",
        (user["id"],)
    )
    report = _fetchone(cur)
    conn.close()

    if not report:
        return jsonify({"error": "No report found yet."}), 404

    return jsonify({
        "report_id": report["id"],
        "overall_score": report["overall_score"],
        "overall_total": report["overall_total"],
        "skills": json.loads(report["skills_breakdown"]),
        "generated_at": report["generated_at"],
        "name": user["name"]
    })


DEFAULT_SKILL_TARGET_PERCENT = 75


def _target_percent_for_designation(designation):
    designation = (designation or "").lower()
    if any(word in designation for word in ("senior", "lead", "head", "principal", "chief")):
        return 85
    if any(word in designation for word in ("intern", "trainee", "junior", "associate")):
        return 65
    return DEFAULT_SKILL_TARGET_PERCENT


def _get_user_row(uid):
    conn = get_db()
    cur = conn.cursor()
    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)
    conn.close()
    return user


@app.route('/api/my_tests/<uid>', methods=['GET'])
def get_my_tests(uid):
    user = _get_user_row(uid)
    if not user:
        return jsonify({"error": "Profile not found."}), 404

    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT * FROM tests WHERE user_id = :1 ORDER BY created_at DESC", (user["id"],)
    )
    tests = _fetchall(cur)

    result = []
    for t in tests:
        cur.execute(
            "SELECT * FROM test_attempts WHERE test_id = :1 ORDER BY taken_at DESC FETCH FIRST 1 ROWS ONLY",
            (t["id"],)
        )
        attempt = _fetchone(cur)

        percent = None
        if attempt and attempt["total"]:
            percent = round((attempt["score"] / attempt["total"]) * 100)

        result.append({
            "test_id": t["id"],
            "difficulty": t["difficulty"],
            "num_questions": t["num_questions"],
            "source_title": t["source_title"],
            "created_at": t["created_at"],
            "score": attempt["score"] if attempt else None,
            "total": attempt["total"] if attempt else None,
            "percent": percent,
            "attempted": attempt is not None,
        })

    conn.close()
    return jsonify(result)


@app.route('/api/test_detail/<int:test_id>', methods=['GET'])
def get_test_detail(test_id):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        """SELECT q.id, q.topic, q.difficulty, q.question_text, q.option_a, q.option_b,
                  q.option_c, q.option_d, q.correct_option, q.explanation, ua.selected_option
           FROM test_questions tq
           JOIN questions q ON q.id = tq.question_id
           LEFT JOIN user_answers ua ON ua.test_id = tq.test_id AND ua.question_id = q.id
           WHERE tq.test_id = :1
           ORDER BY tq.question_order""",
        (test_id,)
    )
    rows = _fetchall(cur)
    conn.close()

    if not rows:
        return jsonify({"error": "Test not found."}), 404

    questions = [{
        "id": r["id"],
        "topic": r["topic"],
        "difficulty": r["difficulty"],
        "question": r["question_text"],
        "options": {"a": r["option_a"], "b": r["option_b"], "c": r["option_c"], "d": r["option_d"]},
        "correct_option": r["correct_option"],
        "explanation": r["explanation"],
        "selected_option": r["selected_option"],
    } for r in rows]

    return jsonify({"test_id": test_id, "questions": questions})


@app.route('/api/skill_radar/<uid>', methods=['GET'])
def get_skill_radar(uid):
    user = _get_user_row(uid)
    if not user:
        return jsonify({"error": "Profile not found."}), 404

    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT skill_name FROM user_skills WHERE user_id = :1", (user["id"],)
    )
    skill_rows = _fetchall(cur)
    declared_skills = [r["skill_name"] for r in skill_rows]

    cur.execute(
        "SELECT skill_name, correct_count, total_count FROM skill_competency WHERE user_id = :1",
        (user["id"],)
    )
    competency_rows = _fetchall(cur)
    conn.close()

    competency_map = {
        r["skill_name"]: round((r["correct_count"] / r["total_count"]) * 100) if r["total_count"] else 0
        for r in competency_rows
    }

    if not competency_map:
        return jsonify({
            "has_data": False, "skills": [],
            "message": "Take a test that covers your skills first."
        })

    skills = [{"skill": name, "percent": competency_map.get(name, 0)} for name in declared_skills]

    return jsonify({"has_data": True, "skills": skills})


@app.route('/api/skill_gap/<uid>', methods=['GET'])
def get_skill_gap(uid):
    user = _get_user_row(uid)
    if not user:
        return jsonify({"error": "Profile not found."}), 404

    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT skill_name FROM user_skills WHERE user_id = :1", (user["id"],)
    )
    skill_rows = _fetchall(cur)
    declared_skills = [r["skill_name"] for r in skill_rows]

    cur.execute(
        "SELECT skill_name, correct_count, total_count FROM skill_competency WHERE user_id = :1",
        (user["id"],)
    )
    competency_rows = _fetchall(cur)
    conn.close()

    competency_map = {
        r["skill_name"]: round((r["correct_count"] / r["total_count"]) * 100) if r["total_count"] else 0
        for r in competency_rows
    }

    if not competency_map:
        return jsonify({"has_data": False, "skills": []})

    target = _target_percent_for_designation(user["designation"])

    gaps = []
    for skill_name in declared_skills:
        current_percent = competency_map.get(skill_name, 0)
        gap = max(0, target - current_percent)
        if gap >= 25:
            priority = "High"
        elif gap >= 10:
            priority = "Medium"
        elif gap > 0:
            priority = "Low"
        else:
            priority = "On Target"
        gaps.append({
            "skill": skill_name,
            "current_percent": current_percent,
            "target_percent": target,
            "gap": gap,
            "priority": priority,
        })

    gaps.sort(key=lambda g: g["gap"], reverse=True)

    return jsonify({"has_data": True, "target_percent": target, "skills": gaps})


@app.route('/api/progress_history/<uid>', methods=['GET'])
def get_progress_history(uid):
    user = _get_user_row(uid)
    if not user:
        return jsonify({"error": "Profile not found."}), 404

    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT overall_percent, taken_at FROM progress_snapshots WHERE user_id = :1 ORDER BY taken_at ASC",
        (user["id"],)
    )
    rows = _fetchall(cur)
    conn.close()

    history = [{"generated_at": r["taken_at"], "percent": r["overall_percent"]} for r in rows]
    return jsonify(history)


def _find_igot_courses(skill_name, limit=3):
    try:
        import sqlite3
        igot_db_path = os.path.join(app.root_path, "igot_courses.db")
        conn = sqlite3.connect(igot_db_path)
        conn.row_factory = sqlite3.Row
        pattern = f"%{skill_name}%"
        rows = conn.execute(
            """SELECT course_name, url, duration, organisation, category
               FROM courses
               WHERE course_name LIKE ? OR description LIKE ? OR category LIKE ?
               ORDER BY course_name
               LIMIT ?""",
            (pattern, pattern, pattern, limit)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _find_tpac_docs(skill_name, limit=3):
    try:
        import sqlite3
        nssta_db_path = os.path.join(app.root_path, "nssta_training.db")
        conn = sqlite3.connect(nssta_db_path)
        conn.row_factory = sqlite3.Row
        pattern = f"%{skill_name}%"
        rows = conn.execute(
            """SELECT subject, reference_id, document_url, start_date, document_type
               FROM tpac_documents
               WHERE subject LIKE ?
               ORDER BY start_date DESC
               LIMIT ?""",
            (pattern, limit)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _get_cached_fallback_topics(skill_name):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT topics_json FROM skill_fallback_topics WHERE skill_name = :1", (skill_name,)
    )
    row = _fetchone(cur)
    conn.close()
    if row and row["topics_json"]:
        topics_json = row["topics_json"]
        if isinstance(topics_json, str):
            return json.loads(topics_json)
    return None


def _cache_fallback_topics(skill_name, topics):
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        """MERGE INTO skill_fallback_topics sft
           USING (SELECT :1 AS skill_name, :2 AS topics_json FROM DUAL) src
           ON (sft.skill_name = src.skill_name)
           WHEN MATCHED THEN UPDATE SET
               sft.topics_json  = src.topics_json,
               sft.generated_at = CURRENT_TIMESTAMP
           WHEN NOT MATCHED THEN INSERT (skill_name, topics_json)
               VALUES (src.skill_name, src.topics_json)""",
        (skill_name, json.dumps(topics))
    )
    conn.commit()
    conn.close()


def _generate_fallback_topics(skill_name):
    cached = _get_cached_fallback_topics(skill_name)
    if cached is not None:
        return cached

    prompt = f"""
    List 5 specific, practical sub-topics a working professional should study to build real
    competency in "{skill_name}". Return ONLY a JSON array of short topic strings (2-5 words
    each), no markdown fences, no commentary.
    """

    try:
        model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=api_key, temperature=0.4)
        response = model.invoke(prompt)
        topics = json.loads(_clean_json_response(response.content))
        topics = [t for t in topics if isinstance(t, str)][:5]
    except Exception as e:
        print(f"Error generating fallback topics for {skill_name}: {str(e)}")
        topics = []

    _cache_fallback_topics(skill_name, topics)
    return topics


@app.route('/api/roadmap/<uid>', methods=['GET'])
def get_roadmap(uid):
    user = _get_user_row(uid)
    if not user:
        return jsonify({"error": "Profile not found."}), 404

    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT skill_name FROM user_skills WHERE user_id = :1", (user["id"],)
    )
    skill_rows = _fetchall(cur)
    declared_skills = [r["skill_name"] for r in skill_rows]

    cur.execute(
        "SELECT skill_name, correct_count, total_count FROM skill_competency WHERE user_id = :1",
        (user["id"],)
    )
    competency_rows = _fetchall(cur)
    conn.close()

    competency_map = {
        r["skill_name"]: round((r["correct_count"] / r["total_count"]) * 100) if r["total_count"] else 0
        for r in competency_rows
    }

    if not competency_map:
        return jsonify({"has_data": False, "skills": []})

    target = _target_percent_for_designation(user["designation"])

    skills_out = []
    for skill_name in declared_skills:
        current_percent = competency_map.get(skill_name, 0)
        gap = max(0, target - current_percent)
        if gap >= 25:
            priority = "High"
        elif gap >= 10:
            priority = "Medium"
        elif gap > 0:
            priority = "Low"
        else:
            priority = "On Target"

        igot_courses = _find_igot_courses(skill_name)
        tpac_docs = _find_tpac_docs(skill_name)

        fallback_topics = []
        if not igot_courses and not tpac_docs and priority != "On Target":
            fallback_topics = _generate_fallback_topics(skill_name)

        skills_out.append({
            "skill": skill_name,
            "current_percent": current_percent,
            "target_percent": target,
            "gap": gap,
            "priority": priority,
            "igot_courses": igot_courses,
            "tpac_docs": tpac_docs,
            "fallback_topics": fallback_topics,
        })

    skills_out.sort(key=lambda s: s["gap"], reverse=True)

    return jsonify({"has_data": True, "target_percent": target, "skills": skills_out})


@app.route('/ask', methods=['POST'])
@require_uid
def ask_question():
    uid = request.uid
    user_question = request.json.get("question")

    store = get_user_vector_store(uid)
    if store is None:
        return jsonify({"answer": "Please process your notes first (Dashboard → upload/pick a book → Process Content)."})

    docs = store.similarity_search(user_question)

    ctx = get_session_context(uid)
    chain = get_conversational_chain(
        ctx["bloom_level"],
        ctx["course_outcomes"],
        ctx["weightage"],
        ctx["language"],
        ctx["study_mode"],
        ctx["vibe_type"]
    )

    response = chain({"input_documents": docs, "question": user_question}, return_only_outputs=True)
    return jsonify({"answer": response["output_text"]})


@app.route('/mode-change', methods=['POST'])
@require_uid
def mode_change():
    data = request.json or {}
    study_mode = data.get("study_mode", "normal")
    vibe_type = data.get("vibe_type", "default")

    update_session_context(request.uid, {"study_mode": study_mode, "vibe_type": vibe_type})

    return jsonify({
        "message": f"Mode changed to {study_mode}",
        "study_mode": study_mode,
        "vibe_type": vibe_type
    })


@app.route('/prioritize_topics', methods=['POST'])
@require_uid
def prioritize_topics():
    uid = request.uid
    store = get_user_vector_store(uid)

    if store is None:
        return jsonify({"error": "Please process a PDF first."}), 400

    try:
        ctx = get_session_context(uid)
        prompt = f"""
        Based on the course content provided, identify and list the main topics covered.
        Prioritize them in ascending order of importance for exam preparation, considering:
        - Course outcomes: {ctx.get('course_outcomes', 'Not specified')}
        - Bloom's level: {ctx.get('bloom_level', 'Not specified')}
        - Topic weightage: {ctx.get('weightage', 'Not specified')} marks

        Return ONLY a numbered list of topics, one per line, starting with the LEAST important
        and ending with the MOST important. Format: just the topic names, no explanations.
        Maximum 10-15 topics.
        """

        docs = store.similarity_search("main topics covered in this course", k=10)

        model = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            google_api_key=api_key,
            temperature=0.3
        )

        context = "\n".join([doc.page_content for doc in docs])
        full_prompt = f"Context:\n{context}\n\n{prompt}"

        response = model.invoke(full_prompt)

        topics_text = response.content
        topics = []

        for line in topics_text.split('\n'):
            line = line.strip()
            if line and not line.startswith('#'):
                cleaned = line.lstrip('0123456789.- )')
                if cleaned:
                    topics.append(cleaned)

        topics = topics[:15]

        return jsonify({"topics": topics})

    except Exception as e:
        print(f"Error in prioritize_topics: {str(e)}")
        return jsonify({"error": "Failed to prioritize topics. Please try again."}), 500


def _latest_reports(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT sr.id, sr.user_id, sr.test_id, sr.overall_score, sr.overall_total,
               sr.skills_breakdown, sr.generated_at,
               u.name, u.department, u.designation
        FROM skill_reports sr
        INNER JOIN (
            SELECT user_id, MAX(generated_at) AS max_date
            FROM skill_reports GROUP BY user_id
        ) latest ON sr.user_id = latest.user_id AND sr.generated_at = latest.max_date
        JOIN users u ON u.id = sr.user_id
    """)
    return _fetchall(cur)


@app.route('/admin/api/departments', methods=['GET'])
@admin_required
def admin_departments():
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        "SELECT DISTINCT department FROM users WHERE department IS NOT NULL AND department != ' ' ORDER BY department"
    )
    rows = _fetchall(cur)
    conn.close()
    return jsonify([r["department"] for r in rows])


@app.route('/admin/api/users', methods=['GET'])
@admin_required
def admin_list_users():
    q = request.args.get("q", "").strip().lower()
    department = request.args.get("department", "").strip()
    status_filter = request.args.get("status", "").strip()
    sort_by = request.args.get("sort_by", "name")

    conn = get_db()
    cur = conn.cursor()
    cur.execute("SELECT * FROM users")
    users = _fetchall(cur)

    reports = _latest_reports(conn)
    conn.close()
    report_map = {r["user_id"]: r for r in reports}

    result = []
    for u in users:
        if q and q not in (u["name"] or "").lower() and q not in (u["email"] or "").lower():
            continue
        if department and (u["department"] or "") != department:
            continue
        user_status = u["status"] or "active"
        if status_filter and user_status != status_filter:
            continue

        report = report_map.get(u["id"])
        percent = None
        if report and report["overall_total"]:
            percent = round((report["overall_score"] / report["overall_total"]) * 100)

        result.append({
            "id": u["id"],
            "uid": u["uid"],
            "name": u["name"],
            "email": u["email"],
            "phone": u["phone"],
            "age": u["age"],
            "department": u["department"] or "Unassigned",
            "designation": u["designation"] or "",
            "status": user_status,
            "score_percent": percent,
            "created_at": u["created_at"],
        })

    if sort_by == "department":
        result.sort(key=lambda x: (x["department"] or "").lower())
    elif sort_by == "score":
        result.sort(key=lambda x: (x["score_percent"] is not None, x["score_percent"] or 0), reverse=True)
    elif sort_by == "created_at":
        result.sort(key=lambda x: str(x["created_at"] or ""), reverse=True)
    else:
        result.sort(key=lambda x: (x["name"] or "").lower())

    return jsonify(result)


@app.route('/admin/api/users/<int:user_id>/status', methods=['POST'])
@admin_required
def admin_update_user_status(user_id):
    data = request.json or {}
    new_status = data.get("status")
    if new_status not in ("active", "disabled"):
        return jsonify({"error": "Status must be 'active' or 'disabled'"}), 400

    conn = get_db()
    cur = conn.cursor()
    cur.execute("UPDATE users SET status = :1 WHERE id = :2", (new_status, user_id))
    updated = cur.rowcount
    conn.commit()
    conn.close()

    if not updated:
        return jsonify({"error": "User not found"}), 404

    verb = "enabled" if new_status == "active" else "disabled"
    return jsonify({"message": f"Account {verb}."})


@app.route('/admin/api/users/<int:user_id>', methods=['DELETE'])
@admin_required
def admin_delete_user(user_id):
    conn = get_db()
    cur = conn.cursor()

    cur.execute("SELECT id FROM users WHERE id = :1", (user_id,))
    existing = _fetchone(cur)
    if not existing:
        conn.close()
        return jsonify({"error": "User not found"}), 404

    cur.execute("DELETE FROM user_education WHERE user_id = :1", (user_id,))
    cur.execute("DELETE FROM user_skills WHERE user_id = :1", (user_id,))
    cur.execute("DELETE FROM user_experience WHERE user_id = :1", (user_id,))
    cur.execute("DELETE FROM skill_reports WHERE user_id = :1", (user_id,))
    cur.execute("DELETE FROM users WHERE id = :1", (user_id,))
    conn.commit()
    conn.close()

    return jsonify({
        "message": "User deleted from BlitzLearn's records. Their login account (Firebase) "
                   "was not removed — that needs to be done separately via Firebase console/Admin SDK."
    })


@app.route('/admin/api/performance', methods=['GET'])
@admin_required
def admin_performance():
    conn = get_db()
    reports = _latest_reports(conn)
    conn.close()

    ranked = []
    for r in reports:
        percent = round((r["overall_score"] / r["overall_total"]) * 100) if r["overall_total"] else 0
        ranked.append({
            "user_id": r["user_id"],
            "name": r["name"],
            "department": r["department"] or "Unassigned",
            "designation": r["designation"] or "",
            "score_percent": percent,
            "score": r["overall_score"],
            "total": r["overall_total"],
        })

    if not ranked:
        return jsonify({"top": None, "bottom": None, "all": []})

    ranked.sort(key=lambda x: x["score_percent"], reverse=True)

    return jsonify({
        "top": ranked[0],
        "bottom": ranked[-1] if len(ranked) > 1 else None,
        "all": ranked,
    })


@app.route('/admin/api/department_report', methods=['GET'])
@admin_required
def admin_department_report():
    conn = get_db()
    cur = conn.cursor()
    cur.execute("SELECT * FROM users")
    users = _fetchall(cur)
    reports = _latest_reports(conn)
    conn.close()

    dept_data = {}
    for u in users:
        dept = u["department"] or "Unassigned"
        dept_data.setdefault(dept, {"user_count": 0, "assessed_count": 0, "scores": [], "skills": {}})
        dept_data[dept]["user_count"] += 1

    for r in reports:
        dept = r["department"] or "Unassigned"
        dept_data.setdefault(dept, {"user_count": 0, "assessed_count": 0, "scores": [], "skills": {}})
        percent = round((r["overall_score"] / r["overall_total"]) * 100) if r["overall_total"] else 0
        dept_data[dept]["assessed_count"] += 1
        dept_data[dept]["scores"].append(percent)

        skills_breakdown = json.loads(r["skills_breakdown"]) if r["skills_breakdown"] else []
        for s in skills_breakdown:
            dept_data[dept]["skills"].setdefault(s["skill"], []).append(s["percent"])

    report = []
    for dept, data in dept_data.items():
        avg_score = round(sum(data["scores"]) / len(data["scores"])) if data["scores"] else None
        skills_avg = [
            {"skill": name, "avg_percent": round(sum(vals) / len(vals))}
            for name, vals in data["skills"].items()
        ]
        skills_avg.sort(key=lambda s: s["avg_percent"])

        report.append({
            "department": dept,
            "user_count": data["user_count"],
            "assessed_count": data["assessed_count"],
            "avg_score_percent": avg_score,
            "skills": skills_avg,
        })

    report.sort(key=lambda d: d["department"])
    return jsonify(report)

@app.route('/api/bootstrap/core', methods=['GET'])
@require_uid
def api_bootstrap_core():
    uid = request.uid
    conn = get_db()
    cur = conn.cursor()

    cur.execute("SELECT COUNT(*) FROM user_vector_chunks WHERE user_uid = :p_uid", {"p_uid": uid})
    processed = cur.fetchone()[0] > 0

    cur.execute(
        "SELECT id, filename, source, title FROM user_staged_files WHERE user_uid = :p_uid ORDER BY created_at",
        {"p_uid": uid}
    )
    staged_files = _fetchall(cur)

    cur.execute('SELECT * FROM users WHERE "UID" = :1', (uid,))
    user = _fetchone(cur)

    profile = None
    skill_radar = {"has_data": False, "skills": []}
    skill_gap = {"has_data": False, "skills": []}
    progress_history = []
    my_tests = []

    if user:
        cur.execute("SELECT id, skill_name, self_rated_level FROM user_skills WHERE user_id = :1", (user["id"],))
        skills = _fetchall(cur)
        cur.execute("SELECT degree, institution, year FROM user_education WHERE user_id = :1", (user["id"],))
        education = _fetchall(cur)
        cur.execute("SELECT role, organization, duration, description FROM user_experience WHERE user_id = :1", (user["id"],))
        experience = _fetchall(cur)

        profile = {
            "name": user["name"], "age": user["age"], "phone": user["phone"], "email": user["email"],
            "department": user["department"], "designation": user["designation"],
            "skills": skills, "education": education, "experience": experience,
        }

        declared_skills = [s["skill_name"] for s in skills]

        cur.execute(
            "SELECT skill_name, correct_count, total_count FROM skill_competency WHERE user_id = :1",
            (user["id"],)
        )
        competency_map = {
            r["skill_name"]: round((r["correct_count"] / r["total_count"]) * 100) if r["total_count"] else 0
            for r in _fetchall(cur)
        }

        if competency_map:
            skill_radar = {
                "has_data": True,
                "skills": [{"skill": name, "percent": competency_map.get(name, 0)} for name in declared_skills]
            }

            target = _target_percent_for_designation(user["designation"])
            gaps = []
            for skill_name in declared_skills:
                current_percent = competency_map.get(skill_name, 0)
                gap = max(0, target - current_percent)
                priority = "High" if gap >= 25 else "Medium" if gap >= 10 else "Low" if gap > 0 else "On Target"
                gaps.append({
                    "skill": skill_name, "current_percent": current_percent,
                    "target_percent": target, "gap": gap, "priority": priority,
                })
            gaps.sort(key=lambda g: g["gap"], reverse=True)
            skill_gap = {"has_data": True, "target_percent": target, "skills": gaps}

        cur.execute(
            "SELECT overall_percent, taken_at FROM progress_snapshots WHERE user_id = :1 ORDER BY taken_at ASC",
            (user["id"],)
        )
        progress_history = [{"generated_at": r["taken_at"], "percent": r["overall_percent"]} for r in _fetchall(cur)]

        cur.execute("SELECT * FROM tests WHERE user_id = :1 ORDER BY created_at DESC", (user["id"],))
        tests = _fetchall(cur)
        for t in tests:
            cur.execute(
                "SELECT * FROM test_attempts WHERE test_id = :1 ORDER BY taken_at DESC FETCH FIRST 1 ROWS ONLY",
                (t["id"],)
            )
            attempt = _fetchone(cur)
            percent = round((attempt["score"] / attempt["total"]) * 100) if attempt and attempt["total"] else None
            my_tests.append({
                "test_id": t["id"], "difficulty": t["difficulty"], "num_questions": t["num_questions"],
                "source_title": t["source_title"], "created_at": t["created_at"],
                "score": attempt["score"] if attempt else None, "total": attempt["total"] if attempt else None,
                "percent": percent, "attempted": attempt is not None,
            })

    conn.close()

    return jsonify({
        "processed": processed,
        "staged_files": staged_files,
        "profile": profile,
        "skill_radar": skill_radar,
        "skill_gap": skill_gap,
        "progress_history": progress_history,
        "my_tests": my_tests,
        "session_context": get_session_context(uid),
    })


@app.route('/api/bootstrap/roadmap', methods=['GET'])
@require_uid
def api_bootstrap_roadmap():
    return get_roadmap(request.uid)


if __name__ == '__main__':
    app.run(debug=True, use_reloader=False, port=5000, host='0.0.0.0')